#!/usr/bin/env bash

set -e

: "${DOCKER:="docker"}"

: "${OPENBAO_IMAGE:="quay.io/openbao/openbao"}"
: "${OPENBAO_VERSION:="2.2.0"}"

: "${VAULT_ADDR:="https://openbao-172.19.0.1.nip.io:8443"}"
: "${VAULT_SKIP_VERIFY:="true"}"

${DOCKER} run \
  --network=host \
  -e VAULT_ADDR="${VAULT_ADDR}" \
  -e VAULT_TOKEN="${VAULT_TOKEN}" \
  -e VAULT_SKIP_VERIFY="${VAULT_SKIP_VERIFY}" \
  "${OPENBAO_IMAGE}:${OPENBAO_VERSION}" \
  "$@"
