#!/usr/bin/env bash

set -e

: "${DOCKER:="docker"}"

: "${OPENBAO_IMAGE:="quay.io/openbao/openbao"}"
: "${OPENBAO_VERSION:="2.2.0"}"

: "${VAULT_ADDR:="http://openbao-127.0.0.1.nip.io:8080"}"

${DOCKER} run \
  --network=host \
  -e VAULT_ADDR="${VAULT_ADDR}" \
  -e VAULT_TOKEN="${VAULT_TOKEN}" \
  ${OPENBAO_IMAGE}:${OPENBAO_VERSION} \
  "$@"
