services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      # https://github.com/keycloak/keycloak-quickstarts/blob/main/kubernetes/keycloak.yaml#L37
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      # KC_HOSTNAME: localhost
      # KC_HOSTNAME_PORT: 7080
      # KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      # KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
#      - "7443:7443"
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
