#!/usr/bin/env bash

set -e

: "${DOCKER:="docker"}"

: "${OPENTOFU_IMAGE:="ghcr.io/opentofu/opentofu"}"
: "${OPENTOFU_VERSION:="1.8.7"}"

: "${TF_VAR_opentofu_state_passphrase:="VERY_SECRET_PASSPHRASE"}" # for testing purposes only!

: "${VAULT_ADDR:="https://openbao-172.19.0.1.nip.io:8443"}"
: "${VAULT_TOKEN:?"Please set VAULT_TOKEN"}"
: "${VAULT_SKIP_VERIFY:="true"}"

${DOCKER} run \
  -it \
  --network=host \
  -u "$(stat -c '%u:%g' "$(pwd)")" \
  --workdir=/srv/workspace \
  --mount type=bind,source=.,target=/srv/workspace \
  --env TF_VAR_opentofu_state_passphrase="${TF_VAR_opentofu_state_passphrase}" \
  --env TF_VAR_openbao_addr="${VAULT_ADDR}" \
  --env TF_VAR_openbao_token="${VAULT_TOKEN}" \
  --env TF_VAR_openbao_skip_tls_verify="${VAULT_SKIP_VERIFY}" \
  "${OPENTOFU_IMAGE}:${OPENTOFU_VERSION}" \
  "$@"
